project:
  type: book
  output-dir: output


book:
  title: "Version Control with Git and GitHub"
  author: 
    - Aud Halbritter
    - Richard J Telford
  date: today
  search: true
  repo-url: https://github.com/biostats-r/biostats
  sharing: [twitter, facebook]
  margin-header: "[![](https://biostats.w.uib.no/files/2020/01/biostats-button-res2.png 'bioST@TS | When biology adds up, at last&#8230;')](https://biostats.w.uib.no/)
   <br>[![](../figures/icons_all.png 'BioST@TS books'){width=250 height=50 fig-alt='Link to biostats books'}](../index.html)"
  chapters:
    - index.qmd
    - 1_Git_Tutorial.qmd
    - 2_Branch_Tutorials.qmd
    - 3_Fork_Tutorial.qmd
    - 4_git_rescue.qmd


highlight-style: a11y

format:
  html:
    code-tools: 
      source: true
      toggle: false
      caption: none
    theme: 
      light: [zephyr, ../css/custom.scss]
      dark: [zephyr, ../css/dark.scss, ../css/custom.scss]
    code-link: true

execute:
  echo: false
  out-width: '100%'
