project:
  type: book
  output-dir: ../docs/


book:
  title: "Enough R to write a thesis"
  subtitle: "From raw data to finished thesis"
  favicon: ../figures/favicon.png
  date: today
  search: true
  repo-url: https://github.com/biostats-r/biostats
  sharing: [twitter, facebook]
  margin-header: "[![](https://biostats.w.uib.no/files/2020/01/biostats-button-res2.png 'bioST@TS | When biology adds up, at last&#8230;'){fig-alt='Link to biostats website'}](https://biostats.w.uib.no/)"
  chapters:
    - index.qmd


format:
  html:
    code-tools: 
      source: true
      toggle: false
      caption: none
    highlight-style: a11y
    theme: 
      light: [zephyr, ../css/custom.scss]
      dark: [zephyr, ../css/dark.scss, ../css/custom.scss]
    code-link: true
    number-sections: false
    
execute: 
  echo: false
