project:
  type: book
  output-dir: ../docs/targets


book:
  title: "Enough targets to Write a Thesis"
  author: "Aud Halbritter, Richard J Telford"
  favicon: ../figures/favicon.png
  date: today
  search: true
  margin-header: "[![](https://biostats.w.uib.no/files/2020/01/biostats-button-res2.png 'bioST@TS | When biology adds up, at last&#8230;')](https://biostats.w.uib.no/)
   <br>[![](../figures/icons_all.png 'BioST@TS books'){width=250 height=50 fig-alt='Link to biostats books'}](../index.html)"
  repo-url: https://github.com/biostats-r/biostats
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - 02-abstraction.qmd
    - 03-workflow.qmd
    - 04-output.qmd

bibliography: reproducibility.bib
suppress-bibliography: true

highlight-style: a11y

format:
  html:
    code-tools:
      source: true
      toggle: false
      caption: none
    theme:
      light: [zephyr, ../css/custom.scss]
      dark: [zephyr, ../css/dark.scss, ../css/custom.scss]
    code-link: true

execute:
  freeze: auto