project:
  type: book
  output-dir: ../docs/data_lifecycle


book:
  title: "Data life cycle"
  author: 
    - Aud Halbritter
  favicon: ../figures/favicon.png
  date: today
  search: true
  repo-url: https://github.com/biostats-r/biostats
  sharing: [twitter, facebook]
  margin-header: "[![](https://biostats.w.uib.no/files/2020/01/biostats-button-res2.png 'bioST@TS | When biology adds up, at last&#8230;')](https://biostats.w.uib.no/)
   <br>[![](../figures/icons_all.png 'BioST@TS books'){width=250 height=50}](../index.html)"
  chapters:
    - index.qmd
    - 01_data_managementplan.qmd
    - 02_design-spreadsheets.qmd
    - 03_data_collection.qmd
    - 04_digitizing_import_data.qmd
    - 05_data_cleaning.qmd
    - 06_communication.qmd
    - 07_death.qmd
    - 08_data_archiving.qmd
    - 09_find_reuse_data.qmd
    
bibliography: bibliography.bib

highlight-style: a11y

format:
  html:
    code-tools: 
      source: true
      toggle: false
      caption: none
    theme: 
      light: [zephyr, ../css/custom.scss]
      dark: [zephyr, ../css/dark.scss, ../css/custom.scss]
    code-link: true
    respect-user-color-scheme: true

execute:
  echo: false
  out-width: '100%'
